### ISSUE TITLE
Page News (ChangeLogs)

### ISSUE THREAD

**Issue by corentin35000** [corentin35000/Crzgames_WebSite_FrontEnd#45]

**Comment by corentin35000** [comment]
- Draw GameCards for all Games.
- Click on a GameCard redirect to: https://crzgames.com/news/title-game/ (new Page)
- View all game changelogs

**Comment by Leoglme** [comment]
![Image](https://github.com/corentin35000/Crzgames_WebSite_FrontEnd/assets/74193170/c657658c-3c4b-4fae-b62b-4905059dc292)



![Image](https://github.com/corentin35000/Crzgames_WebSite_FrontEnd/assets/74193170/e8d7bcb9-28f1-4a21-b592-95f9b0140ebd)

**Comment by Leoglme** [comment]
![Image](https://github.com/corentin35000/Crzgames_WebSite_FrontEnd/assets/74193170/1fb6b2a6-8944-46ed-a91f-095134eb5788)

https://preline.co/examples/blog-articles.html

**Comment by Leoglme** [comment]
04/09/2023 21:59:45 - creation of the feature/45-Page-News-ChangeLogs branch and branch link to issue 45 - Léo Guillaume

**Comment by Leoglme** [comment]
05/09/2023 09:50:31 - creation of the feature/45-Page-News-ChangeLogs branch and branch link to issue 45 - Léo Guillaume

**Comment by Leoglme** [comment]
06/09/2023 01:52:30 - create pull request branch feature/45-Page-News-ChangeLogs to develop - Léo Guillaume. [PR #66](https://github.com/corentin35000/Crzgames_WebSite_FrontEnd/pull/66)
