### ISSUE TITLE
Responsive Mobile for buttons : PC / CONSOLE / MOBILE

### ISSUE THREAD

**Issue by corentin35000** [corentin35000/Crzgames_WebSite_FrontEnd#47]

**Comment by corentin35000** [comment]
- [ ] Responsive Mobile for buttons : PC / CONSOLE / MOBILE

**Comment by Leoglme** [comment]
02/09/2023 01:07:50 - creation of the feature/47-Responsive-Mobile-for-buttons-PC-CONSOLE-MOBILE branch and branch link to issue 47 - Léo Guillaume

**Comment by Leoglme** [comment]
02/09/2023 01:13:26 - create pull request branch feature/47-Responsive-Mobile-for-buttons-PC-CONSOLE-MOBILE to develop - Léo Guillaume. [PR #54](https://github.com/corentin35000/Crzgames_WebSite_FrontEnd/pull/54)
