### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by corentin35000** [corentin35000/Crzgames_WebSite_FrontEnd#48]
https://preline.co/docs/mega-menu.html

**Comment by corentin35000** [comment]
- [ ] Hidden in NavBar : Signup / Signin and display : Signout (et inversement en fonction de si connecté ou non)

**Comment by Leoglme** [comment]
02/09/2023 01:56:27 - creation of the feature/48-NavBar branch and branch link to issue 48 - Léo Guillaume

**Comment by Leoglme** [comment]
02/09/2023 18:14:54 - create pull request branch feature/48-NavBar to develop - Léo Guillaume. [PR #56](https://github.com/corentin35000/Crzgames_WebSite_FrontEnd/pull/56)
