### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by corentin35000** [corentin35000/Crzgames_WebSite_FrontEnd#49]

**Comment by corentin35000** [comment]
- [ ] Delete "github" en bas à droite du github et réadapter si besoin le Footer avec la suppression de cette élément

**Comment by Leoglme** [comment]
02/09/2023 00:02:53 - creation of the feature/49-Footer branch and branch link to issue 49 - Léo Guillaume

**Comment by Leoglme** [comment]
02/09/2023 01:07:32 - create pull request branch feature/49-Footer to develop - Léo Guillaume. [PR #53](https://github.com/corentin35000/Crzgames_WebSite_FrontEnd/pull/53)
