### ISSUE TITLE
Page Account Setting

### ISSUE THREAD

**Issue by corentin35000** [corentin35000/Crzgames_WebSite_FrontEnd#50]
https://preline.co/examples/application-form-layouts.html

**Comment by corentin35000** [comment]
- [ ] Commencer la page ça sera pour modifier username, password..

**Comment by Leoglme** [comment]
04/09/2023 15:35:02 - creation of the feature/50-Page-Account-Setting branch and branch link to issue 50 - Léo Guillaume

**Comment by Leoglme** [comment]
04/09/2023 19:47:52 - create pull request branch feature/50-Page-Account-Setting to develop - Léo Guillaume. [PR #61](https://github.com/corentin35000/Crzgames_WebSite_FrontEnd/pull/61)
